### ISSUE TITLE
Feature request: ability to sell unwanted items after selection

### ISSUE THREAD

**Issue by OmenWild** [IceRaptor/LootMagnet#11]
It would be amazing if there was a sell button next to each item in the assigned loot list that you could click to sell that item/bundle. It would save me having to scroll through the inventory occasionally to get rid of all those medium lasers and small engines.

I know this is not strictly LootMagnet related, but I'm hoping that since you are poking around in related code it might be an "easy" addition. :)

Thanks,
   Omen

**Comment by IceRaptor** [comment]
Fixed with gnivler's quicksell additions.
