### ISSUE TITLE
Feature request to use Custom Component Categories

### ISSUE THREAD

**Issue by LadyAlekto** [IceRaptor/LootMagnet#13]
Base thought is the ability to add CC Categories directly to the restrictions or roll ups and the likes

**Comment by IceRaptor** [comment]
From LA:

so yes to add a category to this "RollupBlacklist": [ and have it automatically not roll that up

chassis and item tags would be nice too (id like to exclude elites, prototypes and omni parts)

**Comment by IceRaptor** [comment]
understandable, it would allow nicely to use its category system, else item and chassistags should go a long way as well without cc

**Comment by IceRaptor** [comment]
Added `LootMagnetComp` in 0.4.1. See GH doco for example.
