### ISSUE TITLE
GetOutcome bug

### ISSUE THREAD

**Issue by Secluse** [IceRaptor/LootMagnet#14]
It appears that the GetOutcome logic is inverted:

public Outcome GetOutcome()
{
	float num = LootMagnet.Random.Next(100);
	if (num < SuccessChance)
	{
		LootMagnet.Mod.Log.Info($"Roll {num} vs. {SuccessChance} is a failure.");
		return Outcome.FAILURE;
	}
	LootMagnet.Mod.Log.Info($"Roll {num} vs. {SuccessChance} is a success.");
	return Outcome.SUCCESS;

Based upon this, the greater the SuccessChance, the greater the chance of failing the roll.

**Comment by IceRaptor** [comment]
Confirmed, fixed, tested.. Will be included in 4.1 release.
