### ISSUE TITLE
RollupFactionMechMulti should be used for Mechs

### ISSUE THREAD

**Issue by peterdettman** [IceRaptor/LootMagnet#2]
Logs show 'Mechs getting rolled up at the same threshold as components. Seems like a simple typo in Helper. GetMechSalvageThreshold, which ought to be referencing RollupFactionMechMulti:

https://github.com/IceRaptor/LootMagnet/blob/60ae64d5005d13b905d76156b6813d78160f3491/LootMagnet/LootMagnet/Utils/Helper.cs#L17

**Comment by IceRaptor** [comment]
Fixed, thank you for the report!
