### ISSUE TITLE
Off-by-one error in holdback random rolls

### ISSUE THREAD

**Issue by peterdettman** [IceRaptor/LootMagnet#3]
In `Helper.HoldbackSalvage`, there are two instances of random rolls against the holdbackChance:

```
                    int roll = LootMagnet.Random.Next(100);
                    if (roll <= holdbackChance) { ... }
```

Random.Next(100) returns a value from 0 to 99, so the comparisons should actually be using `<` instead:

```
                    int roll = LootMagnet.Random.Next(100);
                    if (roll < holdbackChance) { ... }
```

Especially when holdbackChance is 0, the roll should never succeed, and when holdbackChance is 100, it should always succeed. Using '<' gives the correct behaviour.

**Comment by gniewomir** [comment]
Temporary workaround to prevent employer from taking stuff util fix is implemented - use negative multiplier: 

```
        "HoldbackFactionValue" : [ 30, 20, 10, 5, 2.5, -0.001, -0.001, -0.001 ],
```

**Comment by IceRaptor** [comment]
Semantics changed such that holdback is now a trigger, which takes n items. Trigger logic incorporates suggested fix:

``` 
// Check for holdback
float triggerChance = Helper.GetHoldbackTriggerChance();
float holdbackRoll = LootMagnet.Random.Next(101);
if (holdbackRoll <= triggerChance) {
    LootMagnet.Logger.Log($"Holdback triggered from roll:{holdbackRoll} <= triggerChance:{triggerChance}. Removing salvage.");
    modifiedSalvage.AddRange(Helper.HoldbackSalvage(rolledUpSalvage));
} else {
    modifiedSalvage.AddRange(rolledUpSalvage);
}
```

Thanks for the report!

**Comment by peterdettman** [comment]
Thanks for the response, but the code you show doesn't look quite right either. Firstly because `Random.Next(101)` is not a percentile roll: it can return 101 different values, 0 to 100 inclusive. Secondly because if it is corrected to `Random.Next(100)` (0 to 99 inclusive), then you would again need '<' for the comparison with `triggerChance` so that a 0 chance never succeeds (and so that a 99 chance can fail).
