### ISSUE TITLE
Allied status overrides reputation

### ISSUE THREAD

**Issue by peterdettman** [IceRaptor/LootMagnet#4]
Helper.cs has the following code:

```
            // Check for allied
            if (State.IsEmployerAlly) {
                cfgIdx = 7;
            }
```

It seems a little generous for the employer to not distinguish high-rep allies from ones who have "strayed". I propose it be changed to simply give a +1 column shift:

```
            // Check for allied
            if (State.IsEmployerAlly) {
                ++cfgIdx;
            }
```

**Comment by IceRaptor** [comment]
Allying is a binary flag - you either are allied, or you aren't. The game doesn't treat Ally as the end of the spectrum for reputation points, it's a either/or situation. So doing what you propose would lead to weird results, where you are allied in the UI, but using the friendly rep values. 

As such, I'm going to leave as is.
