### ISSUE TITLE
If parts are not rolled up, all salvage of the same type is held back instead of rolling for each part.

### ISSUE THREAD

**Issue by DeltaIII** [IceRaptor/LootMagnet#5]
Because the logic of Helper.RollupSalvageDef does not split up each SalvageDef that does not get rolled up, see L81-84 in Helper.RollupSalvageDef 
https://github.com/IceRaptor/LootMagnet/blob/60ae64d5005d13b905d76156b6813d78160f3491/LootMagnet/LootMagnet/Utils/Helper.cs#L62-L85
the SalvageDef holds _**all**_ salvage of the same type as a single SalvageDef. When this then goes into Helper.HoldbackSalvage all of the parts are held back as a single part!!

For example, if you headshot an assualt mech all 5 partial salvage pieces will be within a single SalvageDef with Count of 5. In Helper.RollupSalvageDef, if the value of each partial piece is above the threshold to rollup, then the SalvageDef is unchanged (all 5 parts remain in the SalvageDef). Now this will obviously end up as one of the most valuable picks, so will likely be the first SalvageDef up to be held back. Then in Helper.HoldbackSalvage, see L107-111 in:
https://github.com/IceRaptor/LootMagnet/blob/60ae64d5005d13b905d76156b6813d78160f3491/LootMagnet/LootMagnet/Utils/Helper.cs#L87-L126
the unchanged SalvageDef is added instead of a _**piece**_ from the SalvageDef (i.e. employer is getting a 5 for 1)!!!!!!!!!

Either Helper.HoldbackSalvage or Helper.RollupSalvageDef should account for unchanged SalvageDef holding more than one part!

**Comment by IceRaptor** [comment]
Holdback now occurs after the player has selected the salvage they intend to keep, so this problem should be minimized. Once 2.0 gets dropped please give it a shot and see if feels more balanced.

Thanks for the report!
