### ISSUE TITLE
Q:  Are rolled up bundles of parts automatically assigned, or do they get broken up?

### ISSUE THREAD

**Issue by Howling-Dog** [IceRaptor/LootMagnet#6]
Setup:  
- Large # of heat sinks available to salvage, rolled up into bundles.
- Player chooses salvage, does not choose heat sink bundle.
- System assigns remaining salvage, including heat sinks.

Q:  Does the player receive bundles of salvaged heat sinks, or do the bundles get broken up and they only receive one?

**Comment by IceRaptor** [comment]
You *should* get the bundled quantity, no matter what. I'll investigate and confirm that, since another bug was discovered that may be impacting that behavior in 2.4.1.

Thanks for the report!

**Comment by IceRaptor** [comment]
This has been fixed in 2.5 and higher. Cheers!
