### ISSUE TITLE
Max Loot Count to certain Equipment

### ISSUE THREAD

**Issue by MachMX** [IceRaptor/LootMagnet#8]
Short Description:
- Add a to limit items from being given as compensation.

Long Description:
Add a way to limit certain equipment from being given as compensation for other salvage.
There are certain equipments, like prototype or extremely scarce equipment that should be limited to be given away easily.

Ex.:
![Example](https://cdn.discordapp.com/attachments/565107929062309888/578457226239410186/armor.png)
A SH drop only armor type which is "supposedly" extremely rare and expensive, being given away like spare change 😆

**Comment by IceRaptor** [comment]
Blacklist added to 2.5 and above.
